name: MSRV

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
  pull_request:
    paths:
      - 'Cargo.toml'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install MSRV toolchain
        run: |
          MSRV=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].rust_version')
          rustup toolchain install "$MSRV" --profile minimal
          rustup override set "$MSRV"

      - name: Build with MSRV
        run: cargo build
